---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty-server-cloudimg-amd64-vagrant-disk1
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: master
    run_list:
      - recipe[pw_testhelper]
      - recipe[pw_jenkins::master]
    attributes:
    driver:
      network:
        - [ 'forwarded_port', { guest: 8080, host: 8080 } ]
        - [ 'private_network', { ip: '192.168.88.100' } ]
  - name: slave
    run_list:
      - recipe[pw_testhelper]
      - recipe[pw_jenkins::slave]
    attributes:
      pw_jenkins:
        slave:
          master_url: 'http://192.168.88.100:8080/jenkins'
          name: 'jkslave'
    driver:
      network:
        - [ 'private_network', { ip: '192.168.88.200' } ]
