name             'pw_jenkins'
maintainer       'Christoph Lukas'
maintainer_email 'christoph.lukas@gmx.net'
license          'All rights reserved'
description      'Installs/Configures jenkins'
long_description 'Installs/Configures jenkins'
version          '0.1.0'

depends 'apt'
depends 'ark'
depends 'pw_base'
depends 'pw_testhelper'
